# Generated by Django 5.0.6 on 2024-05-25 01:05

import apps.investigacion.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Avance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('slug', models.SlugField(default='1', unique=True)),
                ('responsable', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('subcarpetas', models.CharField(blank=True, max_length=250)),
                ('archivo', models.FileField(upload_to=apps.investigacion.models.path_dir)),
                ('slug', models.SlugField(default='1', unique=True)),
                ('avance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivo_del_avance', to='investigacion.avance')),
            ],
        ),
        migrations.CreateModel(
            name='DisciplinasEspecificas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdisciplina_dela_disciplina', to='investigacion.disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_de_finalización_fija', models.BooleanField(default=False)),
                ('fecha_de_finalizacion', models.DateField(default=django.utils.timezone.now)),
                ('publico', models.BooleanField(default=True)),
                ('habilitar_api', models.BooleanField(default=True)),
                ('slug', models.SlugField(default='1', unique=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyecto_dela_disciplina', to='investigacion.disciplina')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyecto_del_equipo', to='equipos.equipo')),
            ],
        ),
        migrations.AddField(
            model_name='avance',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avance_del_proyecto', to='investigacion.proyecto'),
        ),
    ]
