# Generated by Django 5.0.6 on 2024-05-25 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='diciplinas_especificas',
            field=models.ManyToManyField(blank=True, to='investigacion.disciplinasespecificas'),
        ),
    ]
