# Generated by Django 5.0.6 on 2024-05-25 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investigacion', '0002_proyecto_diciplinas_especificas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='fecha_de_finalización_fija',
            new_name='fecha_de_finalizacion_fija',
        ),
    ]
