# Generated by Django 5.0.6 on 2024-05-27 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investigacion', '0003_rename_fecha_de_finalización_fija_proyecto_fecha_de_finalizacion_fija'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('autores', models.ManyToManyField(related_name='autores_libro', to=settings.AUTH_USER_MODEL)),
                ('proyectos', models.ManyToManyField(blank=True, related_name='proyectos_libro', to='investigacion.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superior_de_pagina', models.TextField(blank=True)),
                ('titulo', models.CharField(blank=True, max_length=255)),
                ('numero', models.IntegerField(blank=True, default=1)),
                ('contenido', models.TextField(blank=True)),
                ('pie_de_pagina', models.TextField(blank=True)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libro.libro')),
            ],
        ),
    ]
