# Generated by Django 5.0.6 on 2024-05-25 01:05

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha', models.TimeField(default=datetime.datetime(2024, 5, 25, 1, 5, 18, 817540, tzinfo=datetime.timezone.utc))),
                ('slug', models.SlugField(default=1, unique=True)),
                ('integrantes', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
